[package]
name = "bank_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
serde_json = "1.0.86"
serde = { version = "1.0.147", features = ["derive"] }